# Use the container based trusty distribution
dist: trusty
sudo: false
group: beta

# Set up the conda environment
install:
   - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O ~/miniconda.sh
   - bash ~/miniconda.sh -b -p $HOME/miniconda
   - export PATH="$HOME/miniconda/bin:$PATH"
   - echo $PATH
   - conda env create
   - source activate python_skeleton
   - pip install -e .
   # Use the agg backend to ensure pyqt is not required for testing
   - echo backend:agg > matplotlibrc

script:
   - py.test
